/*
 * ADD A NEW TOOL
 *
 * 1. Client transform: add pure fn in features/client/, add WorkerOp + worker case,
 *    append one entry below with execution: { kind: 'worker', op }, output, paramFields.
 * 2. Backend transform: add FastAPI route, append entry with execution: { kind: 'backend', endpoint }.
 * 3. Editor: append entry with execution: { kind: 'editor', editor: { layout, capabilities } }.
 *
 * No changes needed to ToolWorkspace, runners, param UI, naming, or delivery logic.
 */
import {
  Combine,
  Scissors,
  FileOutput,
  Trash2,
  LayoutGrid,
  RotateCw,
  PenLine,
  Type,
  Image,
  Droplets,
  Lock,
  LockOpen,
  Layers,
  FileImage,
  FileText,
  FileSpreadsheet,
  Presentation,
  ScanText,
  Minimize2,
  Wrench,
} from 'lucide-react'
import { API } from '@/constants/api'
import { MIME } from '@/constants/mime'
import type { ToolDefinition } from '@/features/types'

export const TOOLS: ToolDefinition[] = [
  {
    id: 'merge',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one document.',
    category: 'Organize',
    icon: Combine,
    accepts: 'pdf',
    multiple: true,
    execution: { kind: 'worker', op: 'merge' },
    output: {
      naming: { strategy: 'fixed', name: 'merged.pdf' },
      delivery: 'preview',
      successMessage: 'PDFs merged',
    },
    features: {
      minFiles: 2,
      minFilesMessage: 'Add at least two PDFs to merge',
      inputPreview: true,
    },
  },
  {
    id: 'split',
    name: 'Split PDF',
    description: 'Split in half or extract pages by range.',
    category: 'Organize',
    icon: Scissors,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'split', multiOutput: true },
    output: {
      naming: { strategy: 'derive', suffix: '_split' },
      delivery: 'preview',
      zipName: { suffix: '_splits.zip' },
      successMessage: 'PDF split complete',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'mode',
        label: 'Split mode',
        type: 'select',
        defaultValue: 'half',
        options: [
          { value: 'half', label: 'Split in half' },
          { value: 'pages', label: 'By page ranges' },
        ],
      },
      {
        key: 'ranges',
        label: 'Page ranges',
        type: 'text',
        placeholder: 'e.g. 1-3,5,7-9',
        showWhen: { mode: 'pages' },
        required: true,
      },
    ],
  },
  {
    id: 'extract',
    name: 'Extract Pages',
    description: 'Extract selected pages into a new PDF.',
    category: 'Organize',
    icon: FileOutput,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'extract' },
    output: {
      naming: { strategy: 'derive', prefix: 'extracted_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'Pages extracted',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'ranges',
        label: 'Page ranges',
        type: 'text',
        placeholder: 'e.g. 1-3,5,7-9',
        required: true,
      },
    ],
  },
  {
    id: 'delete-pages',
    name: 'Delete Pages',
    description: 'Remove unwanted pages from a PDF.',
    category: 'Organize',
    icon: Trash2,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'deletePages' },
    output: {
      naming: { strategy: 'derive', prefix: 'trimmed_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'Pages deleted',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'pages',
        label: 'Pages to delete',
        type: 'text',
        placeholder: 'e.g. 2,4,6-8',
        required: true,
      },
    ],
  },
  {
    id: 'organize',
    name: 'Organize PDF',
    description: 'Reorder, rotate, and delete pages visually.',
    category: 'Organize',
    icon: LayoutGrid,
    accepts: 'pdf',
    execution: {
      kind: 'editor',
      editor: {
        layout: 'grid',
        capabilities: ['reorder', 'rotatePage', 'deletePage'],
      },
    },
    output: {
      naming: { strategy: 'derive', prefix: 'organized_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'PDF organized',
    },
    features: { inputPreview: true },
  },
  {
    id: 'rotate',
    name: 'Rotate PDF',
    description: 'Rotate all pages by 90°, 180°, or 270°.',
    category: 'Organize',
    icon: RotateCw,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'rotate' },
    output: {
      naming: { strategy: 'derive', prefix: 'rotated_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'PDF rotated',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'angle',
        label: 'Rotation',
        type: 'select',
        defaultValue: '90',
        options: [
          { value: '90', label: '90° clockwise' },
          { value: '180', label: '180°' },
          { value: '270', label: '270° clockwise' },
        ],
      },
    ],
  },
  {
    id: 'fill-sign',
    name: 'Fill & Sign',
    description: 'Add signatures and fill form fields.',
    category: 'Edit & Sign',
    icon: PenLine,
    accepts: 'pdf',
    execution: {
      kind: 'editor',
      editor: {
        layout: 'overlay',
        capabilities: ['editText', 'signature', 'addText', 'addImage'],
      },
    },
    output: {
      naming: { strategy: 'derive', prefix: 'signed_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'PDF signed',
    },
    features: { inputPreview: true },
  },
  {
    id: 'add-text',
    name: 'Edit Text',
    description: 'Edit existing text or add new text anywhere on your PDF.',
    category: 'Edit & Sign',
    icon: Type,
    accepts: 'pdf',
    execution: {
      kind: 'editor',
      editor: { layout: 'overlay', capabilities: ['editText', 'addText'] },
    },
    output: {
      naming: { strategy: 'derive', prefix: 'edited_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'Text updated',
    },
    features: { inputPreview: true },
  },
  {
    id: 'add-images',
    name: 'Add Images',
    description: 'Place images on PDF pages.',
    category: 'Edit & Sign',
    icon: Image,
    accepts: 'pdf',
    execution: {
      kind: 'editor',
      editor: { layout: 'overlay', capabilities: ['addImage'] },
    },
    output: {
      naming: { strategy: 'derive', prefix: 'with_images_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'Images added',
    },
    features: { inputPreview: true },
  },
  {
    id: 'watermark',
    name: 'Watermark',
    description: 'Add repeating text or image watermarks to every page.',
    category: 'Edit & Sign',
    icon: Droplets,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'watermark' },
    output: {
      naming: { strategy: 'derive', prefix: 'watermarked_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'Watermark applied',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'mode',
        label: 'Watermark type',
        type: 'select',
        defaultValue: 'text',
        options: [
          { value: 'text', label: 'Text' },
          { value: 'image', label: 'Image' },
        ],
      },
      {
        key: 'text',
        label: 'Watermark text',
        type: 'text',
        placeholder: 'CONFIDENTIAL',
        required: true,
        showWhen: { mode: 'text' },
      },
      {
        key: 'fontSize',
        label: 'Font size',
        type: 'number',
        defaultValue: '48',
        min: 12,
        max: 120,
        step: 1,
        showWhen: { mode: 'text' },
      },
      {
        key: 'watermarkImage',
        label: 'Watermark image',
        type: 'file',
        required: true,
        showWhen: { mode: 'image' },
      },
      {
        key: 'imageScale',
        label: 'Image size (% of page width)',
        type: 'number',
        defaultValue: '35',
        min: 10,
        max: 80,
        step: 5,
        showWhen: { mode: 'image' },
      },
      {
        key: 'layout',
        label: 'Layout',
        type: 'select',
        defaultValue: 'tile',
        options: [
          { value: 'tile', label: 'Repeat across page' },
          { value: 'single', label: 'Single (center)' },
        ],
      },
      {
        key: 'opacity',
        label: 'Opacity',
        type: 'number',
        defaultValue: '0.3',
        min: 0,
        max: 1,
        step: 0.1,
      },
    ],
  },
  {
    id: 'password-protect',
    name: 'Password Protect',
    description: 'Encrypt a PDF with a password.',
    category: 'Security',
    icon: Lock,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'passwordProtect' },
    output: {
      naming: { strategy: 'derive', prefix: 'protected_', ext: 'pdf' },
      delivery: 'download',
      successMessage: 'PDF password applied',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'userPassword',
        label: 'Password',
        type: 'password',
        placeholder: 'Enter password',
        required: true,
      },
      {
        key: 'ownerPassword',
        label: 'Owner password (optional)',
        type: 'password',
        placeholder: 'Defaults to user password',
      },
    ],
  },
  {
    id: 'unlock',
    name: 'Unlock PDF',
    description: 'Remove password with the known password.',
    category: 'Security',
    icon: LockOpen,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'unlock' },
    output: {
      naming: { strategy: 'derive', prefix: 'unlocked_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'PDF unlocked',
    },
    features: { inputPreview: true },
    paramFields: [
      {
        key: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Enter PDF password',
        required: true,
      },
    ],
  },
  {
    id: 'flatten',
    name: 'Flatten PDF',
    description: 'Flatten form fields and annotations.',
    category: 'Security',
    icon: Layers,
    accepts: 'pdf',
    execution: { kind: 'worker', op: 'flatten' },
    output: {
      naming: { strategy: 'derive', prefix: 'flattened_', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'PDF flattened',
    },
    features: { inputPreview: true },
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Convert JPG/PNG images into a PDF.',
    category: 'Convert To PDF',
    icon: FileImage,
    accepts: 'image',
    multiple: true,
    execution: { kind: 'worker', op: 'jpgToPdf' },
    output: {
      naming: { strategy: 'fixed', name: 'images.pdf' },
      delivery: 'preview',
      successMessage: 'Images converted to PDF',
    },
  },
  {
    id: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    description: 'Render Markdown or plain text as PDF.',
    category: 'Convert To PDF',
    icon: FileText,
    accepts: 'text',
    execution: { kind: 'worker', op: 'markdownToPdf' },
    output: {
      naming: { strategy: 'derive', ext: 'pdf' },
      delivery: 'preview',
      successMessage: 'Document converted to PDF',
    },
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF to editable DOCX.',
    category: 'Convert From PDF',
    icon: FileText,
    accepts: 'pdf',
    execution: { kind: 'backend', endpoint: API.paths.pdfToWord },
    output: {
      naming: { strategy: 'derive', ext: 'docx' },
      mimeType: MIME.docx,
      delivery: 'download',
      successMessage: 'PDF converted to Word',
    },
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Convert PDF tables to XLSX.',
    category: 'Convert From PDF',
    icon: FileSpreadsheet,
    accepts: 'pdf',
    execution: { kind: 'backend', endpoint: API.paths.pdfToExcel },
    output: {
      naming: { strategy: 'derive', ext: 'xlsx' },
      mimeType: MIME.xlsx,
      delivery: 'download',
      successMessage: 'PDF converted to Excel',
    },
  },
  {
    id: 'pdf-to-ppt',
    name: 'PDF to PowerPoint',
    description: 'Convert PDF slides to PPTX.',
    category: 'Convert From PDF',
    icon: Presentation,
    accepts: 'pdf',
    execution: { kind: 'backend', endpoint: API.paths.pdfToPpt },
    output: {
      naming: { strategy: 'derive', ext: 'pptx' },
      mimeType: MIME.pptx,
      delivery: 'download',
      successMessage: 'PDF converted to PowerPoint',
    },
  },
  {
    id: 'ocr',
    name: 'OCR',
    description: 'Extract searchable text from scanned PDFs.',
    category: 'Optimize & OCR',
    icon: ScanText,
    accepts: 'pdf',
    execution: { kind: 'backend', endpoint: API.paths.ocr },
    output: {
      naming: { strategy: 'derive', prefix: 'ocr_', ext: 'pdf' },
      mimeType: MIME.pdf,
      delivery: 'preview',
      successMessage: 'OCR completed',
    },
    paramFields: [
      {
        key: 'language',
        label: 'Language',
        type: 'select',
        defaultValue: 'eng',
        options: [
          { value: 'eng', label: 'English' },
          { value: 'deu', label: 'German' },
          { value: 'fra', label: 'French' },
          { value: 'spa', label: 'Spanish' },
        ],
      },
    ],
  },
  {
    id: 'compress',
    name: 'Deep Compress',
    description: 'Aggressive file-size reduction via server tools.',
    category: 'Optimize & OCR',
    icon: Minimize2,
    accepts: 'pdf',
    execution: { kind: 'backend', endpoint: API.paths.compress },
    output: {
      naming: { strategy: 'derive', prefix: 'compressed_', ext: 'pdf' },
      mimeType: MIME.pdf,
      delivery: 'preview',
      successMessage: 'PDF compressed',
    },
  },
  {
    id: 'repair',
    name: 'Repair PDF',
    description: 'Fix corrupted or broken PDF files.',
    category: 'Optimize & OCR',
    icon: Wrench,
    accepts: 'pdf',
    execution: { kind: 'backend', endpoint: API.paths.repair },
    output: {
      naming: { strategy: 'derive', prefix: 'repaired_', ext: 'pdf' },
      mimeType: MIME.pdf,
      delivery: 'preview',
      successMessage: 'PDF repaired',
    },
  },
]

export const TOOL_MAP = new Map(TOOLS.map((tool) => [tool.id, tool]))

export function getToolById(id: string): ToolDefinition | undefined {
  return TOOL_MAP.get(id)
}
