export const API = {
  DEFAULT_URL: 'http://localhost:8000',
  DEFAULT_HOST: 'localhost:8000',
  HEALTH_TIMEOUT_MS: 3_000,
  HEALTH_POLL_MS: 30_000,
  HEALTH_STATUS_OK: 'ok',
  paths: {
    health: '/api/health',
    toPdf: '/api/convert/to-pdf',
    imageToPdf: '/api/convert/image-to-pdf',
    pdfToImages: '/api/convert/pdf-to-images',
    pdfToText: '/api/convert/pdf-to-text',
    pdfToHtml: '/api/convert/pdf-to-html',
    pdfToWord: '/api/convert/pdf-to-word',
    pdfToExcel: '/api/convert/pdf-to-excel',
    pdfToPpt: '/api/convert/pdf-to-ppt',
    ocr: '/api/ocr',
    compress: '/api/edit/compress',
    repair: '/api/edit/repair',
  },
} as const
